name: FactionsUI

main: FactionsUI\Main

version: 1.0.2

api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11]

author: QuiverlyRivalry



commands:

 fui:

  description: "FactionsUI, made by Quiv!"
